# blacklist:
# List of blocks that cannot be used to create a SecretDoor or Secret Trapdoor
# whitelist:
# To use the whitelist change enable-whitelist to true
# This setting is disabled by default - it overrides the blacklist and allows for ONLY these blocks to be used as SecretDoors
# List of blocks that can be used as SecretDoors, iff enable-whitelist is true
# Be sure to add the correct fields here - for instance, add SNOW_BLOCK, not SNOW
# Materials reference: http://jd.bukkit.org/beta/apidocs/org/bukkit/Material.html
use-permissions: true
enable-redstone: true
enable-trapdoors: true
enable-timers: false
enable-whitelist: false
close-time-seconds: 5
preserve-attachments: true


blacklist:
  - DISPENSER
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - BARREL
  - CRAFTING_TABLE
  - FURNACE
  - BLAST_FURNACE
  - SMOKER
  - STONE_PRESSURE_PLATE
  - OAK_PRESSURE_PLATE
  - SPRUCE_PRESSURE_PLATE
  - BIRCH_PRESSURE_PLATE
  - JUNGLE_PRESSURE_PLATE
  - ACACIA_PRESSURE_PLATE
  - DARK_OAK_PRESSURE_PLATE
  - MANGROVE_PRESSURE_PLATE
  - CHERRY_PRESSURE_PLATE
  - BAMBOO_PRESSURE_PLATE
  - CRIMSON_PRESSURE_PLATE
  - WARPED_PRESSURE_PLATE
  - REDSTONE_WIRE
  - REDSTONE_TORCH
  - REDSTONE_WALL_TORCH
  - OAK_DOOR
  - IRON_DOOR
whitelist:
  - STONE
  - COBBLESTONE
  - OAK_PLANKS